name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-22.04]
    steps:
      - name: pwd location
        run: pwd
      - name: listing
        run:  ls
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 
      - name: Build docker image
        run: docker build -t madhuraonline/nodejs-notes-app .
      - name: Publish image to docker hub
        run: docker push madhuraonline/nodejs-notes-app:latest
      - name: pwd location
        run: pwd
      - name: listing
        run:  ls
      - name: Set execute permissions for run.sh
        run: chmod +x /root/actions-runner/run.sh
      - name: Start the Runner
        run: /root/actions-runner/run.sh
        
  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull image from docker hub
        run: docker pull madhuraonline/nodejs-notes-app:latest
      - name: Delete old container
        run: docker rm -f nodejs-notes-app-container
      - name: Run docker container
        run: docker run -d -p 5000:5000 --name nodejs-notes-app-container madhuraonline/nodejs-notes-app
